[package]
name = "bevy-balls-demo"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
bevy = "0.5"
bevy_rapier2d = { version = "0.10", features = ["enhanced-determinism"] }
nalgebra = "0.27.1"
rapier2d = { version = "0.9", features = ["enhanced-determinism"] }
